name: AgnHesapEsle
version: 1.2.4
main: me.agnes.agnesesle.AgnesEsle
api-version: 1.13
softdepend: [PlaceholderAPI, LuckPerms]
folia-supported: true
author: Agnes
permissions:
  agnesesle.admin:
    default: opr

